import './globals.css'
import {notoSansTC} from "@/utils/fonts";
import clsx from "clsx";
import {PropsWithChildren} from "react";
export const metadata = {
  title: 'Lingo Pilot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="zh">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
      </head>
      <body className={clsx(notoSansTC.className, notoSansTC.variable, 'bg-primary-900')}>
        {children}
      </body>
    </html>
  )
}
